### ISSUE TITLE
是不是不带tag的时候没法识别？

### ISSUE THREAD

**Issue by hailaz** [rookie-luochao/openapi-ui#177]
![image](https://github.com/rookie-luochao/openapi-ui/assets/29968474/f9742da6-b716-461e-93cf-7796e3813825)

```json
{
  "openapi": "3.0.0",
  "components": {
    "schemas": {
      "main.HelloReq": {
        "properties": {
          "Name": {
            "description": "Your name",
            "format": "string",
            "properties": {
              
            },
            "type": "string"
          }
        },
        "required": [
          "Name"
        ],
        "type": "object"
      },
      "main.HelloRes": {
        "properties": {
          "Reply": {
            "description": "Reply content",
            "format": "string",
            "properties": {
              
            },
            "type": "string"
          }
        },
        "type": "object"
      }
    }
  },
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/hello": {
      "get": {
        "parameters": [
          {
            "description": "Your name",
            "in": "query",
            "name": "Name",
            "required": true,
            "schema": {
              "description": "Your name",
              "format": "string",
              "properties": {
                
              },
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/main.HelloRes"
                }
              }
            },
            "description": ""
          }
        }
      }
    }
  }
}
```

**Comment by rookie-luochao** [comment]
你可以直接用swagger 2.0文档试试吗？我加入了转openapi3的修补功能，可能能避免这种情况

**Comment by rookie-luochao** [comment]
> ![image](https://private-user-images.githubusercontent.com/29968474/328418022-f9742da6-b716-461e-93cf-7796e3813825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDg4MjYsIm5iZiI6MTcxNTE0ODUyNiwicGF0aCI6Ii8yOTk2ODQ3NC8zMjg0MTgwMjItZjk3NDJkYTYtYjcxNi00NjFlLTkzY2YtNzc5NmUzODEzODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2MDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNWQ1YzQxZDViMDRiYTJkMmFjNjhiZmYxZjU4ODEyMmY1NzdiYjM5NzFiZjNjYWJmM2U0M2YxOThmNWIzMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVy2kIUxdiH3Bjds-Wl1f-A6KKwHWQ9t0pkndBE10tk)
> 
> ```json
> {
>   "openapi": "3.0.0",
>   "components": {
>     "schemas": {
>       "main.HelloReq": {
>         "properties": {
>           "Name": {
>             "description": "Your name",
>             "format": "string",
>             "properties": {
>               
>             },
>             "type": "string"
>           }
>         },
>         "required": [
>           "Name"
>         ],
>         "type": "object"
>       },
>       "main.HelloRes": {
>         "properties": {
>           "Reply": {
>             "description": "Reply content",
>             "format": "string",
>             "properties": {
>               
>             },
>             "type": "string"
>           }
>         },
>         "type": "object"
>       }
>     }
>   },
>   "info": {
>     "title": "",
>     "version": ""
>   },
>   "paths": {
>     "/hello": {
>       "get": {
>         "parameters": [
>           {
>             "description": "Your name",
>             "in": "query",
>             "name": "Name",
>             "required": true,
>             "schema": {
>               "description": "Your name",
>               "format": "string",
>               "properties": {
>                 
>               },
>               "type": "string"
>             }
>           }
>         ],
>         "responses": {
>           "200": {
>             "content": {
>               "application/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/main.HelloRes"
>                 }
>               }
>             },
>             "description": ""
>           }
>         }
>       }
>     }
>   }
> }
> ```

已经兼容没有tags的时候，commit [fix: patch operation tags、operationId is undefined](https://github.com/rookie-luochao/openapi-ui/commit/4f8470cf88f12621cd2b0ed3a9bff88f7eb83cf3)

临时预览链接：https://openapi-5ovmq8kst-rookie-luochaos-projects.vercel.app/

**Comment by hailaz** [comment]
临时的链接看不了，要登录，用github登录提示没有账户。等上线再看看

**Comment by rookie-luochao** [comment]
> 临时的链接看不了，要登录，用github登录提示没有账户。等上线再看看

vercel这么恶心人哦，竟然还要登录。
好的，晚上就去发一版，反正现在也没有多少用户，尴尬了！！！

**Comment by rookie-luochao** [comment]
v2.2.1 已经支持无tag的情况，有问题或者好的建议欢迎继续提😁

**Comment by hailaz** [comment]
可以了
