### ISSUE TITLE
界面的文字有些模糊的感觉

### ISSUE THREAD

**Issue by hailaz** [rookie-luochao/openapi-ui#178]
不知道是不是我浏览器的问题，用的edge，感觉字体模糊。
![image](https://github.com/rookie-luochao/openapi-ui/assets/29968474/3efc99e6-f289-4d42-9d04-a7645d55540f)
![image](https://github.com/rookie-luochao/openapi-ui/assets/29968474/7b0da817-c8c1-41ff-8b3a-b8abfce64e90)

**Comment by rookie-luochao** [comment]
我用的mac谷歌浏览器，感觉字体很清晰，我晚上回去把字体在搞大点，用windows测试一下edge

**Comment by rookie-luochao** [comment]
> 不知道是不是我浏览器的问题，用的edge，感觉字体模糊。 ![image](https://private-user-images.githubusercontent.com/29968474/328421117-3efc99e6-f289-4d42-9d04-a7645d55540f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzA3NzgsIm5iZiI6MTcxNTEzMDQ3OCwicGF0aCI6Ii8yOTk2ODQ3NC8zMjg0MjExMTctM2VmYzk5ZTYtZjI4OS00ZDQyLTlkMDQtYTc2NDVkNTU1NDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjAyYzIzNDUzN2IwODM5N2ZmNzc0YmU1ZjhiZDU3ODA1ZWFkNjgwNzEzOTcwNWEzYThhMzE0MmIzMDYzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5gTJzXkX-smAzc5rH9j7uKJzz-4CVIWDAHvL16QJj4w) ![image](https://private-user-images.githubusercontent.com/29968474/328421295-7b0da817-c8c1-41ff-8b3a-b8abfce64e90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzA3NzgsIm5iZiI6MTcxNTEzMDQ3OCwicGF0aCI6Ii8yOTk2ODQ3NC8zMjg0MjEyOTUtN2IwZGE4MTctYzhjMS00MWZmLThiM2EtYjhhYmZjZTY0ZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOTc2ZWQzMWI0MDMwNjNkODg4NjUxY2QyMmJjNWY5OGY5ZDU3Yzg0M2I4N2U2ZGFmOTc2YjJiNGQzZWU4NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aobBUSvCybf7xgAtcvJCYSzNwK4mSRk35y_nbhEo0pk)

我测试了一下，模糊应该是显示器分辨率的原因，在1080p显示器上面就会显得马赛克，尤其是我用习惯了mac的3K分辨率后，感受尤其明显，但是我把工具页的字体设置的尺寸有点小也可能导致你的马赛克体验很明显，我会尝试调大一号字体

还有我看你的截图，你是不是缩放了浏览器的大小（就是command + 加号或者减号）？我怎么感觉你的屏幕视觉特别长

**Comment by hailaz** [comment]
没有缩放，Windows10。图3用谷歌会清晰（截图出来会显得有些模糊）
![image](https://github.com/rookie-luochao/openapi-ui/assets/29968474/f1e79b99-db6f-4981-8c73-a91870593511)
![image](https://github.com/rookie-luochao/openapi-ui/assets/29968474/01c2bfa2-9cb3-47e2-aeb3-f077c92a2408)
![image](https://github.com/rookie-luochao/openapi-ui/assets/29968474/e97db3e0-5e4b-46c1-9984-7e8fa9411fef)

**Comment by rookie-luochao** [comment]
> 没有缩放，Windows10。图3用谷歌会清晰（截图出来会显得有些模糊） ![image](https://private-user-images.githubusercontent.com/29968474/328725508-f1e79b99-db6f-4981-8c73-a91870593511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzM1MjYsIm5iZiI6MTcxNTEzMzIyNiwicGF0aCI6Ii8yOTk2ODQ3NC8zMjg3MjU1MDgtZjFlNzliOTktZGI2Zi00OTgxLThjNzMtYTkxODcwNTkzNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxNTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZDkwZjhjMTQyNWM5Y2I1NGIzN2ViN2YyNTU1MzhlZjlmMTAxMmRhODBhY2UzY2MzYTUwYTE3NmU1YjFhNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2iesaY78XqLQZHfQzBSyBW40oR-jce5VZ-KljyNPSQ) ![image](https://private-user-images.githubusercontent.com/29968474/328725738-01c2bfa2-9cb3-47e2-aeb3-f077c92a2408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzM1MjYsIm5iZiI6MTcxNTEzMzIyNiwicGF0aCI6Ii8yOTk2ODQ3NC8zMjg3MjU3MzgtMDFjMmJmYTItOWNiMy00N2UyLWFlYjMtZjA3N2M5MmEyNDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxNTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDllZjA3MTljNWQ1ZDVmZDU2ODM1YTYwM2ZmODEzOWE4Mzg3NDMxZDI4YjRhODcwNGZjNDU3MTE0NGE2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BTfhJRvlpZhVtW6rf6sdY4G4N33tBZL15C5AZ3YU5dM) ![image](https://private-user-images.githubusercontent.com/29968474/328725961-e97db3e0-5e4b-46c1-9984-7e8fa9411fef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzM1MjYsIm5iZiI6MTcxNTEzMzIyNiwicGF0aCI6Ii8yOTk2ODQ3NC8zMjg3MjU5NjEtZTk3ZGIzZTAtNWU0Yi00NmMxLTk5ODQtN2U4ZmE5NDExZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxNTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OGQxMThhMTQ4ZGNjZTgxZTI2NjA0NGUxM2U4ODUwMDc1MTljZmVhYzZkYjMzYmEwNTI1ZDA2M2RkMzE2OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YGxglBoBy6EPa36wy1AQX1NjbC-JxawuvO4iCF2rKn0)

如果你感觉谷歌显示正常，那可能就是edge的显示表现不一样，考虑到这种情况，我会直接调大号一下字体，可能就能消除模糊重叠的感觉

**Comment by rookie-luochao** [comment]
![image](https://github.com/rookie-luochao/openapi-ui/assets/22948077/cff0c57d-075b-404d-89fe-4fbaa4eb19bc)

这是我1080p截图的 swagger-ui

**Comment by rookie-luochao** [comment]
已经调整部分区域字体大小，commit [style: adjust ui fontSize](https://github.com/rookie-luochao/openapi-ui/commit/61a9dd1fa4514241485b843c413542ec20907dc6)

临时预览链接：https://openapi-5ovmq8kst-rookie-luochaos-projects.vercel.app/

**Comment by rookie-luochao** [comment]
v2.2.1 已经调整字体大小，请体验，有问题或者好的建议欢迎继续提😁

**Comment by hailaz** [comment]
清晰了
