### ISSUE TITLE
bug: body json填写值的时候光标跳到最后面了

### ISSUE THREAD

**Issue by kirileec** [rookie-luochao/openapi-ui#258]
测试使用的是网站上提供的 https://srv-demo-docker.onrender.com/openapi

测试的HelloPost接口

![Clip_2024-08-10_22-35-34](https://github.com/user-attachments/assets/95c63cd9-8df6-4e0e-85a8-39ac672ecf06)

在为name输入值的时候，输入光标会自动跳到最后面，导致无法正常输入

另外，如果这个字段最后面那个引号如果先不输入（也就是整个json如果是不正常的话）不会出现这种情况。感觉是这里编辑器的问题

也不排除是我的环境问题，Chrome隐身模式也是一样的情况

**Comment by rookie-luochao** [comment]
首先回答这个问题：这个光标问题确实是偶尔存在的bug，和编辑器有关
但是你这个简单的输入我不知道为什么也会遇到问题，我按你的步骤操作，复现不出来

我考虑过迁移到更加轻量级的编辑器，无独有偶，仍然有光标问题：[https://github.com/jsonnext/codemirror-json-schema/issues/106](https://github.com/jsonnext/codemirror-json-schema/issues/106)

现在好像开猿节流背景下，开源项目弃坑的越来越多了

如果你想使用我这个工具页并集成到你们的后端框架里面去做接口文档阅读和测试，我很乐意协助你解决问题

**Comment by rookie-luochao** [comment]
这些编辑器提示问题和光标问题，确实都是很难缠的问题，另外一个问题至今也没有解决[https://github.com/jsonnext/codemirror-json-schema/issues/105](https://github.com/jsonnext/codemirror-json-schema/issues/105)

**Comment by rookie-luochao** [comment]
这种简单填写场景，你再换个浏览器试试，看是否会遇到同样的问题？

**Comment by kirileec** [comment]
好的，了解了，你不能复现的话可能真的和浏览器环境有关，我会再去尝试其他浏览器试试看。非常感谢，这个UI真的很棒

**Comment by rookie-luochao** [comment]
谢谢鼓励和反馈，这个光标问题（你的电脑环境是windows吗）？如果你要使用这个UI，你后续有问题都可以继续反馈，很开心和你交流

**Comment by rookie-luochao** [comment]
如果是windows环境必现的bug，我这几天去弄一台window电脑测试一下

**Comment by kirileec** [comment]
是的 我是Windows 11  22621.1928，Chrome版本 127.0.6533.120

**Comment by rookie-luochao** [comment]
同学，请问你还在使用这个工具页面吗？我定位确实windows上面有兼容性问题，我已经修复了

**Comment by rookie-luochao** [comment]
一直没找到windows电脑，然后加班有点多，忘记这个事情了，最近我升级了相关包，然后调试修复了一下这个光标问题

**Comment by rookie-luochao** [comment]
> 是的 我是Windows 11 22621.1928，Chrome版本 127.0.6533.120

大佬，已经在 [v2.3.1](https://github.com/rookie-luochao/openapi-ui/releases/tag/v2.3.1) 修复了输入 body 的光标问题，你可以试试看你的 windows Chrome 还有问题没

**Comment by kirileec** [comment]
@rookie-luochao nice, 已修复
