### ISSUE TITLE
请问下是否可以支持security配置

### ISSUE THREAD

**Issue by LUDA0831** [rookie-luochao/openapi-ui#289]
在swagger-ui中可以显示一把锁,调试的时候自动带入请求头,openapi-ui在修改配置里填上Authorization调试时也不会带上Authorization:Bearer 请求头
![image](https://github.com/user-attachments/assets/0d84e465-d11e-4d32-8d59-0c56ea74873c)
![image](https://github.com/user-attachments/assets/218f8f63-aaaa-483f-9b4d-d2d4b03ec646)

**Comment by rookie-luochao** [comment]
<img width="670" alt="image" src="https://github.com/user-attachments/assets/a49106da-4a55-4aa2-adbe-83055c1a1e06">
请问通过这个配置传入 Authorization 不能在Header里面加入Authorization？

**Comment by rookie-luochao** [comment]
<img width="799" alt="image" src="https://github.com/user-attachments/assets/9b8ccd26-a913-4ce2-bb32-0abd89909de8">
在这里填入token

**Comment by rookie-luochao** [comment]
如果你的问题是想要自动填充Token，那我需要修改一下，你能否告诉我在哪里能取到token？

**Comment by LUDA0831** [comment]
> <img alt="image" width="799" src="https://private-user-images.githubusercontent.com/22948077/371384373-9b8ccd26-a913-4ce2-bb32-0abd89909de8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDk1OTEsIm5iZiI6MTcyNzQwOTI5MSwicGF0aCI6Ii8yMjk0ODA3Ny8zNzEzODQzNzMtOWI4Y2NkMjYtYTkxMy00Y2UyLWJiMzItMGFiZDg5OTA5ZGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAzNTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTg2ZGY5YWIwODY1ZTQ1YzliZDQ1NTJkMTA1NzQyNzgwZjg4MDE5ODFiMTQ0ZDA0MzdjZGY2MTQ1MjJiMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fg5jIZ7YyrpdcxGo7AqZajEGxHnFk32zufwe86mDdfA"> 在这里填入token

是的,已经在这里填上了token,在点击请求的时候没有在Header里面加入Authorization

**Comment by rookie-luochao** [comment]
你这个 openapi 对接口的定义是不是 header 里面并没有 Authorization 的定义，属于要取security的配置(这个相当于全局配置)
```json
"parameters": [
          {
            "name": "applyEnvID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "description": "申请环境",
              "x-go-field-name": "ApplyEnvID",
              "x-tag-name": "applyEnvID"
            }
          },
          {
            "name": "Authorization",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "minLength": 1,
              "description": "`bearer ${Token}`",
              "x-go-field-name": "Authorization",
              "x-tag-name": "Authorization",
              "x-tag-validate": "@char[1,]"
            }
          },
        ]
```

**Comment by LUDA0831** [comment]
应该是的,全局定义一次,在需要认证的接口上可以复用
swagger-ui是可以支持这种方式的,复用了的接口就会显示一把锁
![image](https://github.com/user-attachments/assets/467aeda1-3668-447d-ab32-826a639025d1)
![image](https://github.com/user-attachments/assets/9cb30570-be59-441c-ad10-f4d142385984)
![image](https://github.com/user-attachments/assets/17639b42-2074-4a47-8dab-b9865aabda20)
![image](https://github.com/user-attachments/assets/c9bcf633-9a97-4479-a2cd-fbf09304f85c)

**Comment by rookie-luochao** [comment]
请问我暂时改成让全局配置 Authorization 生效可以暂时解决你的问题吗？
这个security功能我可能要思考一下再加

**Comment by LUDA0831** [comment]
感谢🤝,可以的,如果配置了Authorization默认每个请求头都添加Authorization: Bearer ${token} 这种jwt格式的可以解决问题
![image](https://github.com/user-attachments/assets/e7a44f0d-f76f-4234-8a5f-14f6a756bf16)

**Comment by rookie-luochao** [comment]
> 感谢🤝,可以的,如果配置了Authorization默认每个请求头都添加Authorization: Bearer ${token} 这种jwt格式的可以解决问题 ![image](https://private-user-images.githubusercontent.com/45849881/371427068-e7a44f0d-f76f-4234-8a5f-14f6a756bf16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjA5MDEsIm5iZiI6MTcyNzQyMDYwMSwicGF0aCI6Ii80NTg0OTg4MS8zNzE0MjcwNjgtZTdhNDRmMGQtZjc2Zi00MjM0LThhNWYtMTRmNmE3NTZiZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNzI0MjkzOTliNmMxMjlkZDQ2ZThjMWY2NDQ5ZTUzZmI1MWQxZTIyYWFkZDQ1Y2ZhZmE2ODE3YTNiMTA0MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lt6yprIEkktqf9qQI7hAvO3Q9tXG2nyP4-k7VGqxBxM)

没问题，请问你要如何使用呢，你是直接使用的这个工具页面吗? www.openapi-ui.com

**Comment by LUDA0831** [comment]
是CDN方式使用的
![image](https://github.com/user-attachments/assets/aa8af615-fafc-45f6-bbd1-608fa6bce2ae)

**Comment by rookie-luochao** [comment]
> 是CDN方式使用的 ![image](https://private-user-images.githubusercontent.com/45849881/371430840-aa8af615-fafc-45f6-bbd1-608fa6bce2ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjE0NjAsIm5iZiI6MTcyNzQyMTE2MCwicGF0aCI6Ii80NTg0OTg4MS8zNzE0MzA4NDAtYWE4YWY2MTUtZmFmYy00NWY2LWJiZDEtNjA4ZmE2YmNlMmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc2ZWU1ZmQ5M2Y2MjhhZjE5YTc3M2RhMWVkZTYyYzIxZDE5NGRhMzFkZDJmMjU3Y2Y0MWVhNzQwMDBmZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1ASuseVzXwjkpX4sA85SCCfx44H56mOZxSxvEcwY1E8)

已经发布新版本了，你试试呢

**Comment by LUDA0831** [comment]
感谢,工具页面已经可以了,cdn还不行估计还没同步,我晚点在试下🤝

**Comment by rookie-luochao** [comment]
> 感谢,工具页面已经可以了,cdn还不行估计还没同步,我晚点在试下🤝

不客气哈，能帮助到你就行，有问题再提issue反馈哈，我会全力协助，对你有帮助，请帮忙给个小星星

**Comment by rookie-luochao** [comment]
> 谢谢,已点小星星👍

感谢👍
