### ISSUE TITLE
使用apifox导出的 openapi 3.0格式的文档，导入到系统中，无法加载

### ISSUE THREAD

**Issue by hp198410** [rookie-luochao/openapi-ui#303]
上传之后， 页面空白，并且也无任何错误提示

**Comment by rookie-luochao** [comment]
根据提供的 openapi.json 配置文件观察发现，很多必要信息都没有，比如：operationId、tags，需要处理兼容一下

**Comment by rookie-luochao** [comment]
已经在 [v2.3.2](https://github.com/rookie-luochao/openapi-ui/releases/tag/v2.3.2) 修复
