### ISSUE TITLE
枚举类型值展示

### ISSUE THREAD

**Issue by lurenyang418** [rookie-luochao/openapi-ui#305]
目前只有类型，希望能将值暴露出来
<img width="253" alt="image" src="https://github.com/user-attachments/assets/b72b0da0-1109-4c15-8087-3ac149d5396b">

React 不太熟悉， 本地拉取修改后 build 失败

<img width="249" alt="image" src="https://github.com/user-attachments/assets/5654876f-9506-4e96-8332-3e07fad90e18">

**Comment by rookie-luochao** [comment]
你的枚举值没有展示出来吗？请问可以给我的邮箱发送一份配置文件吗？我帮你看看

**Comment by rookie-luochao** [comment]
<img width="635" alt="image" src="https://github.com/user-attachments/assets/1ccb6d75-7bd4-46e9-9e47-e5725ca155b5">
你应该是想展示这些枚举值吗？支持枚举的，要看你的配置文件是否满足，可能没支持到

**Comment by lurenyang418** [comment]
<img width="472" alt="截屏2024-10-12 17 05 40" src="https://github.com/user-attachments/assets/ba02c30c-3efe-407d-b06b-e3d8e413a9b8">

swagger-ui 是可以展示出来的

api.json 中的数据(部分)如下
``` json
{
    "properties": {
        "org_id": {
            "format": "uint64",
            "type": "integer"
        },
        "name": {
            "format": "string",
            "type": "string"
        },
        "org_type": {
            "enum": [
                "hospital",
                "self_company"
            ],
            "format": "enums.OrgType",
            "type": "string"
        }
    },
    "required": [
        "org_id",
        "name",
        "org_type"
    ],
    "type": "object"
}
```

**Comment by rookie-luochao** [comment]
> <img alt="截屏2024-10-12 17 05 40" width="472" src="https://private-user-images.githubusercontent.com/15855043/375944736-ba02c30c-3efe-407d-b06b-e3d8e413a9b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjU0NTAsIm5iZiI6MTcyODcyNTE1MCwicGF0aCI6Ii8xNTg1NTA0My8zNzU5NDQ3MzYtYmEwMmMzMGMtM2VmZS00MDdkLWIwNmItZTNkOGU0MTNhOWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YmMwMzU1NWE4OGIxODBlZmZkNzNhNzM4YmVjOTcwMDM5ZmUxN2E2NWI5MTEyMWY3NTgzMTBkYmQyZDc4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NphCoYjBZ8gnSjeejGjzN_VCGB7XYQi20zodKphr2sk">
> swagger-ui 是可以展示出来的
> 
> api.json 中的数据(部分)如下
> 
> ```json
> {
>     "properties": {
>         "org_id": {
>             "format": "uint64",
>             "type": "integer"
>         },
>         "name": {
>             "format": "string",
>             "type": "string"
>         },
>         "org_type": {
>             "enum": [
>                 "hospital",
>                 "self_company"
>             ],
>             "format": "enums.OrgType",
>             "type": "string"
>         }
>     },
>     "required": [
>         "org_id",
>         "name",
>         "org_type"
>     ],
>     "type": "object"
> }
> ```

请问可以邮箱发我一份openapi.json配置吗，我来定位下问题？

**Comment by lurenyang418** [comment]
重新开了个新的

[api.json](https://github.com/user-attachments/files/17349804/api.json)

**Comment by rookie-luochao** [comment]
好的，定位到问题并兼容和给你说😁😁😁

**Comment by rookie-luochao** [comment]
已经在 [v2.3.3](https://github.com/rookie-luochao/openapi-ui/releases) 修复

**Comment by rookie-luochao** [comment]
同学，bug已经修复，请查收
